name: Lint
on: [pull_request]
env:
  NODE_VERSION: 22

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS 22
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm run ci
      - name: Run ESLint
        run: npm run lint
